name: fse
description: Flutter services example
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: 1.1.2
  environment_config: 2.2.4
  get_it: 5.0.1
  google_fonts: 1.1.0
  http: 0.12.2
  json_annotation: 3.1.0
  liquid_pull_to_refresh: 2.0.0
  provider: 4.3.2+2
  shared_preferences: 0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.1
  json_serializable: 3.5.0
  pedantic: 1.9.0
  redux_remote_devtools: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
